# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rDZSMBcQbdGHfut6KS4GNmmJV5sMLx71
"""

#string=input()
string='energetic'
first_char=string[0]
#print(first_char)
rest_string=string[1:]
#print(rest_string)
replace_string=rest_string.replace(first_char,'$')
#print(final_string)
print(first_char + replace_string )