# -*- coding: utf-8 -*-
"""4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oUvboCStYmUVjx4I1q9Pyuoo1beGwNr8
"""

pattern_size = 4
#part1
for i in range(0, pattern_size):
  for j in range(0, i+1):
    print("*", end='')
  print("\n")
#part2
for i in range(pattern_size,0,-1):
  for j in range(0,i-1):
    print("*",end='')
  print("\n")