# -*- coding: utf-8 -*-
"""5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMJzco9m298t2Umhpbj78twX_TbLTVcM
"""

start=25
end=50

print("Prime numbers between",start,"and",end,"are:")   
for n in range(start,end+1):  
   if n>1:  
       for i in range(2,n):  
           if(n%i)==0:  
            break  
       else:  
           print(n)