# -*- coding: utf-8 -*-
"""6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18qtsCM2E0FUMOlrTWAnlvnc9Tfcsc3po
"""

listOne = [3, 6, 9, 12, 15, 18, 21] 
listTwo = [4, 8, 12, 16, 20, 24, 28]

odd_index=[]
even_index=[]

odd_index=listOne[1::2]
even_index=listTwo[0::2]

listThree=[]
#listThree.append(odd_index) 
#print(listThree)

listThree.extend(odd_index) 
listThree.extend(even_index) 
print("Element at odd-index positions from list one:", odd_index)
print("Element at even-index positions from list two:" ,even_index)
print("Printing Final third list:",listThree)