# -*- coding: utf-8 -*-
"""7-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xz98_FfllsdPYWstnHtnpeL6t1vBHMoH
"""

import matplotlib.pyplot as plt 
  
Toothpaste = [2500,2630,2140,3400,3600,2760] 
Facewash = [1500,1200,1340,1130,1740,1555] 
Shampoo = [5200,5100,4550,5870,4560,4890] 
Moisturizer = [9200,6100,9550,8870,7760,7490] 
Soap = [1200,2100,3550,1870,1560,1890] 
Month = [1,2,3,4,5,6]

plt.figure(figsize=(10, 8))

plt.plot(Month,Toothpaste, label = "Toothpaste") 

plt.plot(Month,Facewash, label = "Facewash") 

plt.plot(Month,Shampoo, label = "Shampoo") 

plt.plot(Month,Moisturizer, label = "Moisturizer") 
 
plt.plot(Month,Soap, label = "Soap") 

plt.xlabel('Month no.') 

plt.ylabel('Sales unit') 

plt.title('6 Month’s sales data for different products') 

plt.legend(loc='upper right') 

plt.show()